package it.ictgroup.asr.management;

public enum AppKeys
{
   TIPOLOGIA_FLUSSO, TIPOLOGIA_FLUSSO_1, TIPOLOGIA_FLUSSO_2, NOME_FILE, ELABORAZIONE_ID, ELABORAZIONE_ID_1, ELABORAZIONE_ID_2, INVIO_ID, NOME_FOLDER
}
